### ISSUE TITLE
API removed for `aiven_flink_table`

### ISSUE THREAD

**Issue by Dariusch** [aiven/terraform-provider-aiven#1056]
## What happened?

I tried to create an `aiven_flink_table` in version 3.11.0 of the provider and I get:

```shell
│ Error: 404: {"errors":[{"message":"The API has been removed.","status":404}],"message":"The API has been removed."} -
```

## What did you expect to happen?

- the API being available for a stable version of the provider
- A Flink table is being created

## What else do we need to know?

My provider version: "3.11.0"
Resouce: [`aiven_flink_table`](https://registry.terraform.io/providers/aiven/aiven/3.11.0/docs/resources/flink_table)

Seems like the backward compatibility is broken as the stable v4.0.0 release is not available yet.
The [example](https://github.com/aiven/terraform-provider-aiven/blob/main/examples/flink/main.tf) seems to be out of date as well

Will there be a replacement for the `aiven_flink_table` and `aiven_flink_job` resources?

**Comment by byashimov** [comment]
Hey.
Unfortunately we can't remove deprecated resources due to the terraform's deprecation policy (must be done with a major release).
New resources are [aiven_flink_application](https://registry.terraform.io/providers/aiven/aiven/3.12.0/docs/resources/flink_application) and [aiven_flink_application_version](https://registry.terraform.io/providers/aiven/aiven/3.12.0/docs/resources/flink_application_version).
Please update the provider to 3.12, it's been just released :)
