### ISSUE TITLE
Aiven kafka topic optional configuration not to fail if topic exists

### ISSUE THREAD

**Issue by jmespinosa** [aiven/terraform-provider-aiven#1378]
## What is currently missing?

At the moment we are using Kafka mainly to communicate between some systems, meaning that a topic doesn't belong to a specific system deployment, but is shared between 2 or more so if we deploy the first, the the second will fail on creation as the topic exists already

## How could this be improved?

I would include an optional configuration, sort of:
 "doNotFailIfTopicExists" = ( true | false ). 
 - false by default, so it works as currently
 - when true and the topic exists:
     - If the topic config is the same, it does nothing
     - If the topic config is different, then fail, as currently

## Is this a feature you would work on yourself?

   Not in principle, but I'll think about it

**Comment by Serpentiel** [comment]
hey, @jmespinosa! 👋

could you please provide an example manifest to help us to understand the situation better?

thank you!

**Comment by jmespinosa** [comment]
This was opened as a possible enhancement rather that a bug.  

For instance we have in one of our self contained system this:
```
resource "aiven_kafka_topic" "my_topics" {
  for_each = toset(local.my_topics)

  project                = my_project
  service_name           = my_kafka_service
  topic_name             = my_topic_name
  partitions             = 3
  replication            = 2
  termination_protection = false

  config {
    flush_ms       = 10
    cleanup_policy = "delete"
  }

  timeouts {
    create = "3m"
    read   = "5m"
  }
}
```
And then we have something similar in another system with its own kafka topics, but some of the topics are common, because both systems use them to communicate.
If I deploy the first system, creates the topics, and when I deploy the second one and tries to create them, already exist, and fail.
The only alternative I see is to have a separate terraform project that takes care of creating the kafka topics exclusively, and run it manually.  But in this case we lose the concept of having any independent system to create everything it needs at deployment time.

**Comment by Serpentiel** [comment]
hey, @jmespinosa! 👋

thank you so much for the detailed context and the illustrative example! it's always super valuable to understand the practical challenges users face in order to improve our tooling effectively

while the `doNotFailIfTopicExists` option seems like a straightforward and practical solution on the surface, it's essential to mention that this approach diverges a bit from Terraform’s foundational principles, especially concerning predictability and explicit resource management

Terraform generally anticipates maintaining comprehensive control over the resources it manages, ensuring the real-world state of a resource consistently aligns with the configuration outlined in the Terraform files

implementing a feature that instructs Terraform to overlook certain inconsistencies (such as a pre-existing resource it was supposed to create) might introduce unexpected complexities and behaviors, particularly in larger, multifaceted infrastructures where multiple systems and teams are deploying resources

a widespread pattern to handle shared resources in Terraform involves creating a separate project (or module) to manage these shared entities

the state from this dedicated project can be accessed by other projects using [remote state](https://developer.hashicorp.com/terraform/language/state/remote-state-data), ensuring a consistent view of the shared resource across all systems interfacing with it, without allowing direct management over it.

here’s a quick example using remote state:

```hcl
data "terraform_remote_state" "shared" {
  backend = "s3"
  config = {
    bucket = "my-terraform-state"
    key    = "path/to/my/key"
    region = "us-west-2"
  }
}

output "topic_name" {
  value = data.terraform_remote_state.shared.outputs.my_topic_name
}
```

this approach allows you to segregate the management of shared resources (like Kafka topics) from the systems that utilize them, while still maintaining the capability for those systems to be aware of and interact with the shared resources

I totally understand that this might not exactly align with the entirely self-contained deployment method per system you’re looking for, but it should provide a safe and predictable mechanism for managing shared resources across multiple systems and projects

your feedback is absolutely invaluable and we remain open to further dialogue and insights on how we can enhance the user experience while staying true to Terraform’s foundational principles
