### ISSUE TITLE
Handle missing aiven_mysql_user resource gracefully

### ISSUE THREAD

**Issue by joonvena** [aiven/terraform-provider-aiven#1401]
## What happened?

When user is removed manually from the console running `terraform plan` at that point returns `Error: user xx/xx/xx not found`.

## What did you expect to happen?

It should handle the situation gracefully and create the resource again. It works this way with `aiven_pg_user` as it calls the [ResourceReadHandleNotFound](https://github.com/aiven/terraform-provider-aiven/blob/main/internal/schemautil/service.go#L832) function 

## What else do we need to know?

To reproduce create `aiven_mysql_user` resource and delete the user manually from the console. Then execute `terraform plan` again and error should pop up.

**Comment by Serpentiel** [comment]
hey, @joonvena! 👋

thank you for reporting this issue!

it's important to note that Terraform is designed to be the single source of truth for infrastructure provisioning and management; this means that changes to the infrastructure should be made via Terraform configurations and applied using Terraform commands, rather than being made manually outside of Terraform, and making changes outside of Terraform can lead to the state of the infrastructure diverging from the state defined in Terraform configurations, which can cause errors like the one you're experiencing

in this specific case, when a user is manually deleted from the console, Terraform's state file still believes the user exists; when you run `terraform plan`, it checks the actual state of the infrastructure against the state file, finds that the user is missing, and returns an error

the recommended approach here is to make changes to your infrastructure by modifying your Terraform configurations and then applying those changes with `terraform apply`—this way, the Terraform state file will always be in sync with the actual state of your infrastructure, and you can avoid issues like the one you've described

if you've already manually deleted the user and are now facing this error, you will need to either manually re-create the user to match the Terraform state, or update your Terraform configurations to remove the user and then run `terraform apply` to sync the state file with the actual state of the infrastructure

**Comment by joonvena** [comment]
Thanks for the reply @Serpentiel!

Yes, i know this but the provider should still handle it gracefully. This is the default with pretty much every other provider when the resource is deleted outside Terraform it would be recreated instead returning error that is missing. This is also the case with the `aiven_pg_user` resource so why it is handled with the pg user but with mysql not?

My current problem with it is that i have created [Crossplane](https://www.crossplane.io/) provider for the Aiven and when trying to create mysql user resource it fails as it doesn't handle the missing resource gracefully. Works just fine with the pg.

Just wanted to give more context to the issue.

**Comment by Serpentiel** [comment]
hey, @joonvena! 👋

after additional consideration, we've decided to add support for it :)

I'll prepare a PR shortly!

**Comment by Serpentiel** [comment]
hey, @joonvena! 👋

I've introduced a PR which fixes this problem
