### ISSUE TITLE
Provide Kafka SASL connect uri on aiven_kafka

### ISSUE THREAD

**Issue by gpkc** [aiven/terraform-provider-aiven#1444]
## What is currently missing?

There doesn't seem to be any output from `aiven_kafka` that provides the SASL connect uri.
Currently, you have to do a workaround like:

```
locals {
  sasl_uri = [for component in aiven_kafka.kafka.components :
  "${component.host}:${component.port}" if component.kafka_authentication_method == "sasl"]
}
```

## Is this a feature you would work on yourself?

* [ ] I plan to open a pull request for this feature.

**Comment by Serpentiel** [comment]
Hey, @gpkc! 👋

Thank you for bringing this issue up!

I will be taking a look at this issue now, I will let you know if we have any additional questions or concerns

**Comment by Serpentiel** [comment]
Hey, @gpkc! 👋 

I have created a PR which adds this feature and it's now being reviewed by our team!

Hopefully this is going to be merged soon. If this is something urgent to you, you may as well try to build the provider manually from the source code

Otherwise please expect to see this feature soon, unless the team has anything against this implementation

**Comment by Serpentiel** [comment]
Hey, @gpkc! 👋 

The PR was just merged, please expect to see this released soon!

**Comment by gpkc** [comment]
That's awesome thanks! :) I will already use it in production as soon as it's released
