### ISSUE TITLE
Aiven authentication resource

### ISSUE THREAD

**Issue by the-real-mathew-moon** [aiven/terraform-provider-aiven#1759]
Looks like the `account_authentication` resource was deprecated in [this PR](https://github.com/aiven/terraform-provider-aiven/pull/1620) with little to no explanation as to why in the PR or the CHANGELOG.md.

1. Why is this removed?
2. What is the intended replacement?

**Comment by rsalevsky** [comment]
Hello, over the last months we have added several new features to authentication methods and significantly improved how an authentication methods is setup in the Aiven Console. The new features would have required significant changes to the TF resource which would make the usage of the TF resource rather complex. In order to provide a simple and uniform user experience we decided to direct all customers to setup an authentication method in the Aiven Console. In the Aiven Console you can experience a step by step wizard which guides you through the setup process with detailed explanations on what the individual settings mean. 

https://aiven.io/docs/platform/howto/saml/add-identity-providers
