### ISSUE TITLE
data  "aiven_kafka" return wrong service_port

### ISSUE THREAD

**Issue by kuzm1ch** [aiven/terraform-provider-aiven#1849]
data resource "aiven_kafka" return wrong service_port(and as a result "service_uri"). 

## Example
service_uri from resource:
`service_uri":"****.j.aivencloud.com:28613"`

kafka_uri in aiven console: 
![Screenshot 2024-09-23 at 15 59 09](https://github.com/user-attachments/assets/8bfe845b-9d2b-4e97-9a4e-4cf29db5eaf4)

provider version: 4.25.0 
Terraform v1.9.4

**Comment by richard-joerger-aiven** [comment]
We confirmed that this is the default and expected behaviour of Aiven API resource [ServiceGet](https://api.aiven.io/doc/#tag/Service/operation/ServiceGet). As a result, every Aiven Kafka service has high-level metadata including the default service_uri and service_port based on SSL authentication, even after you disabled it. In order to get the connection URI to use by your Kafka clients based on aiven_kafka resource state, you need to read it from the components section instead:
```
$ terraform state show aiven_kafka.kafka1
# aiven_kafka.kafka1:
resource "aiven_kafka" "kafka1" {
    components              = [
        {
            component                   = "kafka"
            connection_uri              = "<my_host>:<my_port>"
            host                        = "<my_host>"
            kafka_authentication_method = "sasl"
            port                        = <my_port>

        },
    ]
}
```
