### ISSUE TITLE
VPC Referencing

### ISSUE THREAD

**Issue by encima** [aiven/terraform-provider-aiven#203]
> As an Aiven user I would like to be able to reference "aiven_project_vpc" in the same way as the canonical google way (the self_link attribute) so that I do not have to convert between the Aiven and canonical Google format.

**Comment by ivan-savciuc** [comment]
Indeed GCP TF provider has a `self_link` attribute for nearly every resource, which is a is a unique reference to that resource. On the other hand, Aiven supports multiple cloud providers, and for example, AWS and Azure do not have a concept of `self_link`, and it looks like it is solely supported by GCP. 

Can you please provide an example of how can we implement this so that GCP users can benefit from that without any shortcomings for other cloud provider users? Concrete examples are welcome.

**Comment by encima** [comment]
I will be working on documentation for this, with examples, as it can be built with using the state_info object in a fairly uniform way but requires monitoring the status and building manually. 

Perhaps we can include a helper to build a Google URL when the status is PENDING_PEER?

**Comment by ivan-savciuc** [comment]
We can definitely add a helper field to build a Google URI if we would have all information coming from Aiven API to construct it on the fly.

**Comment by bkamin29** [comment]
Hello guys, your discussion is about this ? : 

When i have to create a VPC peering on Google to my Aiven VPC, i have to "compute" the vpc_self_link of the Aiven VPC in Google, like that : 

```
resource "aiven_project_vpc" "main" {
  project      = var.aiven_project_id
  cloud_name   = "google"
  network_cidr = "192.168.0.0/24"
}

resource "google_compute_network" "vpc_network" {
  name    = "vpc-network"
  project = var.gcp_project_id
}

resource "aiven_vpc_peering_connection" "main" {
  vpc_id             = aiven_project_vpc.main.id
  peer_cloud_account = var.gcp_project_id
  peer_vpc           = google_compute_network.vpc_network.self_link
}

resource "google_compute_network_peering" "main" {
  name         = "aiven-network"
  network      = google_compute_network.vpc_network.self_link
  peer_network = "https://www.googleapis.com/compute/v1/projects/${aiven_vpc_peering_connection.main.state_info.to_project_id}/global/networks/${aiven_vpc_peering_connection.main.state_info.to_vpc_network}"
}
```
