### ISSUE TITLE
Database resource fails when applying 

### ISSUE THREAD

**Issue by riechst1** [aiven/terraform-provider-aiven#236]
Not sure if anyone has come across an issue when using the `aiven_database`  resource it fails to apply with the following error :

`* aiven_database.test: 501: {"errors":[{"message":"An error occurred. Please try again later.","status":501}],"message":"An error occurred. Please try again later."} -`

Code Block:
resource "aiven_database" "test" {
	project = "${data.terraform_remote_state.timescale_project.project_name}"
	service_name = "${aiven_service.db.service_name}"
	database_name = "test"
}

Simple and nothing complicated. Plan looks as the following:

Terraform will perform the following actions:

  + aiven_database.sample_db
      id:                                  <computed>
      database_name:                "test"
      project:                               "test"
      service_name:                   "delta"

Providers Version:
Terraform : `0.11.14`
Aiven : `1.0.18` and `1.2.4`
aws : `2.64`

Any suggestion is greatly appreciated.

**Comment by ivan-savciuc** [comment]
This issue is specific only for Timescale Cloud, as we can see from an error message and our internal investigation that Aiven API respond with 501 HTTP Response code when a user tries to create a database in Timescale Cloud. The database itself is created, but there is a bug on API side which triggers this error, that is why on the next attempt to create a database Terraform complains that such database already exists.

There is nothing that we can do on the Terraform Provider side to make it work, and it will start working automatically when this issue will be addressed on Aiven API side.
