### ISSUE TITLE
Validate Kafka Topic Replication Factor

### ISSUE THREAD

**Issue by galvo** [aiven/terraform-provider-aiven#252]
When a Kafka Topic is configured with a replication count of less than 2 then terraform plan will accept it but will later error out with 

Error: 400: {"errors":[{"message":"Replication factor must be set to at least two","status":400}],"message":"Replication factor must be set to at least two"}

It would be useful if validation could be applied so that you can't execute on the plan until a valid replication count is entered.

```
resource "aiven_kafka_topic" "testTopic" {
  project = var.aiven_project_name
  service_name = aiven_service.kafka-service1.service_name
  topic_name = "test-topic"
  partitions = 1
  replication = 1
  cleanup_policy = "compact"
}
```

**Comment by ivan-savciuc** [comment]
Hi @galvo,

According to Aiven documentation, https://api.aiven.io/doc/#operation/Service___Kafka.ServiceKafkaTopicCreate replication can be `>= 1`. Therefore, Terraform Provider is correctly validating your code. 

You are getting this error because according to our business logic if a service has more, then one node in a cluster replication factor should be `>=2`.

It is not something that we can track in Terraform and consequently improve validation because one resource knows nothing about another.
