### ISSUE TITLE
Upgrading Provider to v2.0.0 error with aiven_vpc_peering_connection unsupported attribute "peer_azure_app_id"

### ISSUE THREAD

**Issue by phumberdroz** [aiven/terraform-provider-aiven#289]
Upgrade to v2.0.0 causes problems with aiven_vpc_peering_connection I am also using terraform v0.13 in connection with this but I think that is unrelated since v1.3.4 of this provider still works fine with terraform v0.13 it is unrelated. 

```
➜ tf plan

Error: Invalid resource instance data in state

  on aiven_timescale.tf line 8:
   8: resource "aiven_vpc_peering_connection" "k8s" {

Instance aiven_vpc_peering_connection.k8s data could not be decoded from the
state: unsupported attribute "peer_azure_app_id".


Error: Invalid resource instance data in state

  on aiven_timescale.tf line 8:
   8: resource "aiven_vpc_peering_connection" "k8s" {

Instance aiven_vpc_peering_connection.k8s data could not be decoded from the
state: unsupported attribute "peer_azure_app_id".

Releasing state lock. This may take a few moments...
```

**Comment by ivan-savciuc** [comment]
`v1.3.5` is built on the old Terraform github.com/hashicorp/terraform and `v2.0.0` is using Terraform Plugin SDK ithub.com/hashicorp/terraform-plugin-sdk which is compatible with Terraform 0.13 client and utilizes all the latest 0.13 TF state developments. It is the only change that was introduced with the v2 if we are talking about VPC peering connections. 

Perhaps it is somehow related to Terraform client 0.13.0 and in particular to https://github.com/hashicorp/terraform/pull/25779, and I lets see if this issue will be fixed with the release of Terraform client 0.13.1. In the meanwhile, I'll try to reproduce this issue on my box.

**Comment by ivan-savciuc** [comment]
@phumberdroz can you still reproduce this issues with the latest Terraform client version https://github.com/hashicorp/terraform/releases/tag/v0.13.3?

**Comment by phumberdroz** [comment]
I will check early next week.

**Comment by phumberdroz** [comment]
Seems to be working 👍
