### ISSUE TITLE
Broken after Upgrade

### ISSUE THREAD

**Issue by simonharrer** [aiven/terraform-provider-aiven#31]
Used the plugin from ... for provisioning a kafka 2.0 service with users and topics, which worked fine. I'm using S3 as a backend for the terraform configuration.

Switched to your plugin with version 1.0.1 and fixed the syntax changes in the terraform script. 

Now, I get the following crash when I run `terraform plan`

```
panic: runtime error: index out of range
2018-10-19T09:19:52.718Z [DEBUG] plugin.terraform-provider-aiven: 
2018/10/19 09:19:52 [ERROR] root: eval: *terraform.EvalRefresh, err: aiven_service.my-kafka: unexpected EOF
2018-10-19T09:19:52.719Z [DEBUG] plugin.terraform-provider-aiven: goroutine 41 [running]:
2018/10/19 09:19:52 [ERROR] root: eval: *terraform.EvalSequence, err: aiven_service.my-kafka: unexpected EOF
2018/10/19 09:19:52 [TRACE] [walkRefresh] Exiting eval tree: aiven_service.my-kafka
2018/10/19 09:19:52 [TRACE] root: eval: *terraform.EvalIf
2018/10/19 09:19:52 [TRACE] root: eval: *terraform.EvalCountFixZeroOneBoundary
2018/10/19 09:19:52 [TRACE] Graph after step *terraform.ReferenceTransformer:
```

Can you help?

**Comment by rikonen** [comment]
The old Terraform plugin you were using wasn't officially supported by us and only supported limited subset of Aiven features. The new officially supported versions (1.0.0, 1.0.1) are not compatible with the old unsupported versions because there were numerous changes related to the way how ids are managed and how service specific attributes are accessed that were not possible to do in backwards compatible manner.

There isn't any detailed guide for upgrading from an older version but the new readme and sample script should show fairly comprehensively what is the correct way of defining resources with the new version. Because the identifiers have changed it is not possible to use an existing Terraform state but you will instead need to remove the old terraform state file and then import the existing resources with `terraform import <terraform_id> <aiven_id>` command. https://help.aiven.io/services/aiven-terraform-integration also has some additional instructions.
