### ISSUE TITLE
Implement "default_acl" attribute to "aiven_service" TF resource 

### ISSUE THREAD

**Issue by bkamin29** [aiven/terraform-provider-aiven#355]
Hello,

Could you please implement the attribute `default_acl` (usefull for Kafka only) to the TF resource `aiven_service` ?
It's already available for the resource `aiven_kafka`.

The TF resource `aiven_service` is always interesting because we can use it to create an agnostic terraform module who can deals with all services types available on Aiven side. In this module we can mutualize source code.

Thank you in advance,

Benjamin

**Comment by ivan-savciuc** [comment]
Hello Benjamin, we recommend using `aiven_kafka` instead of `aiven_service`, and unfortunately, it will be deprecated in the coming future. For the sake of simplicity, we decided to split `aiven_service` to separate service-specific resources, and it looks like most of our customers prefer it this way. We left `aiven_service` resource for backward compatibility reasons for the customers upgrading from v1.
