### ISSUE TITLE
Upgrade v2.1.1 to v2.1.2

### ISSUE THREAD

**Issue by mced** [aiven/terraform-provider-aiven#432]
I'm trying to figure out the path to upgrade to the latest aiven provider version but I'm stuck at v2.1.1.
Indeed, upgrading provider from v2.1.1 to v2.1.2 causes a problem on `card_id` attribute on resource `aiven_project`.

```
$ terraform plan
...
Error: Error getting long card id: 404: Card with ID ********-****-****-****-************ not found - 
...
```

I've got the same problem after removing the attribute `card_id`.

The v2.1.1 and v2.1.2 documentations tells that attribute is still optional.

Do you have helpful insights to resolve that behavior ?
Thanks

**Comment by ivan-savciuc** [comment]
Please try `v2.1.4` or our latest version, if you do not have a dedicated billing group associated with this project. 

Recently Aiven has introduced Billing Groups which has many billing-related filed from a project, now moved to a separate entity. We do not recommend using project fields like `card_id` (already deprecated starting from `v2.1.4`).

If you have a dedicated billing group associated with this project, please remove a `card_id` from a billing group.

**Comment by mced** [comment]
I installed v2.1.5, removed the resource from the state, edit the resource and then reimport it. But still I've a an error on card id while importing it... The resource is referenced in another resources. The terraform version is v.0.13.6.

```
$ terraform init
$ terraform state rm aiven_project.default
$ terraform import 'aiven_project.default' *************
aiven_project.default: Importing from ID "*************"...
aiven_project.default: Import prepared!
  Prepared aiven_project for import
aiven_project.default: Refreshing state... [id=*************]
```

```
resource "aiven_project" "default" {
  project          = data.sops_file.secrets.data["aiven.project-id"]
  default_cloud    = "aws-eu-central-1"
}
```

**Comment by ivan-savciuc** [comment]
Just thinking logically: 
- It looks like `aiven_project.default` has a wrong `card_id`, and the value is coming from API.
- You cannon set it empty/remove it since TF refresh is running before `apply` by default.
- Since the resource was deleted from the state and now imported, it will have none empty `card_id` coming from API and import is triggering `refresh` which will always result in an error because of the broken `card_id`.

If `aiven_project.default` wouldn't be deleted from the state, we had a chance to run `terraform apply -refresh=false` with `card_id` empty to remove it for good.

In this situation, I believe we do not have any options to resolve it on the TF side, and I would recommend going to the Aiven Consol and remove the broken card from this project (this can be done in the Billing section). Then again remove it from the state and import.

**Comment by ivan-savciuc** [comment]
Besides that, we will update the `refresh` logic to avoid such situations in the future. It is indeed annoying that you cannot remove a broken card from Terraform.

**Comment by mced** [comment]
Ok thanks !
