### ISSUE TITLE
aiven_service_user does not honor redis acls

### ISSUE THREAD

**Issue by grounded042** [aiven/terraform-provider-aiven#447]
I'm setting up a user for redis with the following properties:
```
  redis_acl_categories = [
    "+@all",
    "-@dangerous",
  ]
  redis_acl_commands = []
  redis_acl_keys     = []
```
Terraform will show that these changes will be applied, but after the apply completes when I check the UI I see
![image](https://user-images.githubusercontent.com/1075622/109345252-166c7480-782d-11eb-8c19-87aecc844029.png)

If I re-plan it shows the changes again. If I apply the same things happens.

**Comment by ivan-savciuc** [comment]
This problem seems to be related to an Aiven API. If we use a console instead of Terraform and create a new user with Redis ACL category: `-@dangerous` result will be the same, without getting any error well get Categories: `+@all -@admin` and Commands: `-swapdb -migrate -flushall -keys -restore -flushdb -restore-asking -info -sort -role` out of the blue.

After spending some time testing, we also found other issues of a similar nature but not necessarily related to `-@dangerous`. 

I have created an internal issue to fix that on the Aiven API side.

**Comment by grounded042** [comment]
Hey @ivan-savciuc any update on a timeline for this?

**Comment by ivan-savciuc** [comment]
Hey @grounded042, we have two internal tickets related to this issue, and both of them are currently in progress. When both of them will be tested, reviewed, and deployed I'll let you know.

These changes are back-end related and don't require any changes on the Terraform since, when deployed everything should just start working.

**Comment by davidespo** [comment]
@grounded042 sorry for the delay. This issue was fixed on the Aiven API side on Mar. 23. Sorry we did not include a reply here. Can you please verify the fix in your environment as well? I was not able to reproduce the issue.

**Comment by grounded042** [comment]
@davidespo I just tested it out and we are all good now. Thanks!
