### ISSUE TITLE
Wrong type rendering between schema and the docs

### ISSUE THREAD

**Issue by z0r1k** [aiven/terraform-provider-aiven#620]
Hi,

In the schema (https://github.com/aiven/terraform-provider-aiven/blob/c0182fce7e2af8869d5877031a2f82ec7704c04a/aiven/templates/service_user_config_schema.json#L4508-L4511) type is defined as list of `null` and `boolean`. 

I assume when property is not set default value is `null` and the main use-case is to have it set to `true` or `false` if one would use it. 
When docs are being generated aforementioned type is being rendered as `string` instead - https://github.com/aiven/terraform-provider-aiven/blob/c0182fce7e2af8869d5877031a2f82ec7704c04a/docs/resources/service.md#L948
This is a big misleading. 

It seems to happen to other properties as well. 

Ty.

**Comment by ivan-savciuc** [comment]
@z0r1k, we know about this issue, all user configuration options have the type `string` in Terraform. We auto-generate all of them from the JSON schema you mentioned above. And our documentation is generated based on resource schema, which is why you get this issue. 

We plan to rework the generation of user configuration options which will automatically fix this issue.

**Comment by Serpentiel** [comment]
after further evaluation, due to the deprecation mandate from Hashicorp, we will be unable to change those types in v3.x, and this will only be adjusted in v4.0, which is currently an on-going project of ours

**Comment by Serpentiel** [comment]
v4 was released, and the docs were adjusted accordingly
