### ISSUE TITLE
`v3.9.0` : existing `ip_filter` gets destroyed because of `ip_filter_object`

### ISSUE THREAD

**Issue by wanisfahmyDE** [aiven/terraform-provider-aiven#987]
after upgrading to `v3.9.0` terraform destroys the existing  `ip_filter`  attribute in `aiven_kafka` and adds an empty `ip_filter_object` removing all IP filtering from our kafka cluster!

plan output:

```terraform

 ~ kafka_user_config {
          ~ ip_filter                 = [
              + "xx.xx.xx.xx/xx",
              + "xx.xx.xx.xx/xx",
              + "xx.xx.xx.xx/xx"
            ]
            # (6 unchanged attributes hidden)

          - ip_filter_object {
              - network = "xx.xx.xx.xx/xx" -> null
            }
          - ip_filter_object {
              - network = "xx.xx.xx.xx/xx" -> null
            }
          - ip_filter_object {
              - network = "xx.xx.xx.xx/xx" -> null
            }

            # (3 unchanged blocks hidden)
        }

```

checking the aiven console event log, all IPs were removed

This problem exists when there is some IPs managed in the UI and the rest in terraform, which was not a problem before 3.9.0

**Comment by wanisfahmyDE** [comment]
update: even after switching to the new ip_filter_object in a fresh setup, adding an IP in the UI totally messes up the terraform plan and mixes the IPs and removes some..

**Comment by Serpentiel** [comment]
hey, @wanisfahmyDE! 👋 

this has now been acknowledged by the team members, and has been confirmed to be a bug

I will now investigate possible solutions to this

**Comment by wanisfahmyDE** [comment]
Hi @Serpentiel,

Any updates on that? I see there is a new release v.3.10.0 but I am not sure if there is a fix included in it

**Comment by Serpentiel** [comment]
hey, @wanisfahmyDE! 👋 

sorry, but the PR that was supposed to address the problem has appeared to introduce other problems in certain places

if it is possible to use v3.8.1 for now, I would recommend doing so, thank you!

**Comment by ivan-savciuc** [comment]
hey @wanisfahmyDE, the problem with `ip_filter_object` is that API returns items of this list in a different order than you have in the Terraform manifest. We are working to fix that issue in the upcoming release. So please stick to the previous version until we supply you with the patch.

**Comment by ivan-savciuc** [comment]
The whole story: since you are using web UI to change some IDs, the UI automatically converts ip_filters to the objects, causing problems. Everything should work if you created a service using `ip_filter` without changing anything outside of Terraform.

**Comment by Serpentiel** [comment]
hey, @wanisfahmyDE 👋

I have created a PR that will address your issue, however there are several things that I would like to note:

- the PR adds support for the proper usage of `ip_filter_object` setups, as it appeared to be originally implemented incompletely

- the usage of multiple API clients such as, in your case, Terraform and the Web UI is actually discouraged by Hashicorp—the developer of Terraform—so I would not advice managing resources as you described, but since you already manage your resources in this manner, you will have to adjust your manifests to use `ip_filter_object` instead, since the Web UI overrides `[]string` `ip_filter` options and saves them in `[]struct{network string; description string}` format instead, and we are unable to address this problem due to the fact that Hashicorp mandates against the usage of multiple IaaC tools when using Terraform (in your case, Terraform and Web UI) to be able to provide versioning of resources

**Comment by wanisfahmyDE** [comment]
hey @Serpentiel,

Thanks for your reply and for the PR! When this is merged, we will extend our manifests to use the `ip_filter_object`

What would be the expected behaviour after adapting? deletion of the old `ip_filter` resources and creation of `ip_filter_object` in one terraform apply hit?

Just some background, we're a platform team that provides a terraform module on top of your provider to our teams. We have already a bunch of IPs set in this module as a sensible default that are relevant to our org.
Teams use our module to provision clusters and topics, but also use the Aiven Console to quickly filter their IPs when they want to do local development against a publicly accessible Aiven Kafka. For these reasons, we are not in control of what teams would do in the console separately, we can only advice not to.

**Comment by Serpentiel** [comment]
hey, @wanisfahmyDE! 👋

the PR that addresses the problem has been merged, if there is an urgency, you're welcome to build it from the source on your own

otherwise, we will be shipping a new release in the upcoming days

please let me know if the issue persists! :)

<br>
<br>
<br>

> deletion of the old ip_filter resources and creation of ip_filter_object in one terraform apply hit?

iiuc, this should do the trick, but if it doesn't, you're free to do that in multiple steps

> For these reasons, we are not in control of what teams would do in the console separately, we can only advice not to.

I would recommend to advice not to manage resources this way, although I understand it might not always be posible

you could probably also use Terraform Cloud to get rid of this problem

**Comment by wanisfahmyDE** [comment]
@ivan-savciuc @Serpentiel any ETA on the release for this fix?

**Comment by Serpentiel** [comment]
hey, @wanisfahmyDE! 👋

the new version is out now!

**Comment by joaocc** [comment]
Hi. Just posted on another topic, and this issue still seems to occur. What would be the correct interface to manage this? Thx
